class ExpressionHandler:
    MAPPING = {
        "binh_thuong": "Ngồi yên",
        "cam_on": "Cảm ơn",
        "xin_chao": "Xin chào",
        "yeu": "Yêu",
        "khong": "Không",
        "toi": "Tôi",
        "ten_la": "Tên là",
        "tuoi": "tuổi",
        "rat_vui_duoc_gap_ban": "rất vui được gặp bạn",
        "hen_gap_lai": "hẹn gặp lại",
        "cau_hoi": "câu hỏi",
        "khoe": "khỏe",
        "ban": "bạn",
        "den_tu": "đến từ",
        "gia_dinh": "gia đình",
        "ranh": "rảnh",
        "ban": "bạn",
        "an": "ăn",
        "banj": "bận",
        "di": "đi",
        "lam": "làm",
        "gio": "giờ",
        "quang_binh": "Quảng Bình",
        "thanh_pho_hue": "Thành phố Huế",
        "hoc_tap": "học tập",
        "giup_do": "giúp đỡ",
        "ngur": "ngủ",
        "xin_loi": "xin lỗi",
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "a": "a",
        "b": "b",
        "c": "c",
        "d": "d",
        "e": "e",
        "g": "g",
        "h": "h",
        "i": "i",
        "k": "k",
        "l": "l",
        "n": "n",
        "m": "m",
        "o": "o",
        "p": "p",
        "q": "q",
        "r": "r",
        "u": "u",
        "v": "v",
        "t": "t",
        "ngay_thuong_binh_lietsi": "ngày thương bình liệt sĩ 27/7",
        "ngay_gio_to_hungvuong": "ngày giỗ tổ Hùng Vương (âm lịch 10/3)",
        "ngay_ngon_ngu_ki_hieu_quocte": "ngày Ngôn ngữ kí hiệu Quốc tế 23/9",
        "tuan_le_nguoi_diec_thegioi": "tuần lễ người Điếc thế giới",
        "ngay_cua_me": "ngày của Mẹ",
        "ngay_cua_cha": "ngày của Cha",
        "ngay_gia_dinh_vn": "ngày gia đình Việt Nam 28/6",
        "noi_da_ga": "nổi da gà",
        "ghen_ti": "ghen tị",
        "lung_tung": "lung tung",
        "hoi_dau": "hói đầu",
        "cuoi_nhech_mep": "cười nhếch mép",
        "cuoi_vo_bung": "cười vỡ bụng",
        "tham_an": "tham ăn",
        "them": "thèm",
        "them_ro_dai": "thèm rỏ dãi",
        "dung_dau": "đứng đầu (hàng đầu)",
        "thoi_quen": "thói quen",
        "No hands/face detected": "❌ Không phát hiện tay/mặt",
        "Error in detection": "⚠️ Lỗi phát hiện",
        "a_rap": "Ả Rập",
        "dia_chi": "Địa chỉ",
        "do_thai": "Do Thái",
        "dubai": "Dubai",
        "ma_cao": "Ma Cao",
        "mien_dien": "Miến Điện",
        "nguoi_nuoc_ngoai": "Người nước ngoài",
        "nhan_vien": "Nhân viên",
        "nhap_khau": "Nhập khẩu",
        "phuong_dong": "Phương Đông",
        "phuong_tay": "Phương Tây",
        "quy_nhon": "Quy Nhơn",
        "tiep_tan": "Tiếp tân",
        "tinh": "Tỉnh",
        "tuy_hoa": "Tuy Hòa",
        "khuyen_khich": "Khuyến khích",
        "khong_nghe_loi": "Không nghe lời",
        "ai_cho": "Ai cho",
        "khong_cho": "Không cho",
        "khong_can": "Không cần",
        "khong_nen": "Không nên",
        "buc_minh": "Bực mình",
        "tu_giac": "Tự giác",
        "mu_chu": "Mù chữ",
        "vo_tinh": "Vô tình",
        "tet_han_thuc": "Tết Hàn Thực",
        "quoc_te_phu_nu": "ngày Quốc tế phụ nữ 8/3",
        "giai_phong_thu_do": "Ngày giải phóng thủ đô 10/10",
        "giai_phong_mien_nam": "Ngày giải phóng miền Nam 30/4",
        "nguoi_khuyet_tat_viet_nam_18_4": "ngày Người khuyết tật Việt Nam 18/4",
        "nguoi_khuyet_tat_the_gioi_3_12": "ngày Người khuyết tật Thế giới 3/12",
        "halloween": "lễ Halloween 31/10",
        "ngay_phu_nu_viet_nam": "ngày Phụ nữ Việt Nam 20/10",
        "ban_yeu_toi": "Bạn yêu tôi",
        "toi_yeu_ban_ay": "Tôi yêu bạn ấy",
        "ban_ay_yeu_toi": "Bạn ấy yêu tôi",
        "ban_yeu_ban_ay": "Bạn yêu bạn ấy",
        "ban_ay_yeu_ban": "Bạn ấy yêu bạn",
        "anh_hai_anh_ca": "Anh hai, anh cả",
        "chi_hai_chi_ca": "Chị hai, chị cả",
        "qua_bau_ho_lo": "Quả bầu hồ lô",
        "mot_la": "Một là",
        "hai_la": "Hai là",
        "ba_la": "Ba là",
        "bon_la": "Bốn là",
        "nam_la": "Năm là",
        "ong_ba": "Ông bà",
        "em_ho": "Em họ",
        "chau_ho": "Cháu họ",
        "song_sot": "Sống sót",
        "thuong_xuyen": "Thường xuyên",
        "di_dao": "Đi dạo",
        "ve_sai_gon": "Về (Sài Gòn)",
        "phong_toa": "Phong toả",
        "thung_lung": "Thung lũng",
        "dia_hinh": "Địa hình",
        "kim_dong": "Kim đồng",
        "thanh_giong": "Thánh gióng",
        "hoa_giay": "Hoa giấy",
        "hoa_dam_but": "Hoa dâm bụt",
        "ket_luan": "Kết luận",
        "internet": "Internet",
        "di_ve_sinh": "Đi vệ sinh",
        "hoa_mai": "Hoa mai",
        "aw": "ă",
        "aa": "â",
        "b": "b",
        "c": "c",
        "d": "d",
        "dd": "đ",
        "ow": "ơ",
        "dau_huyen": "Dấu huyền",
        "dau_sac": "Dấu sắc",
        "dau_hoi": "Dấu hỏi",
        "dau_nang": "Dấu nặng",
        "khong_co": "Không có",
        "khong_co_chi": "Không có chi",
        "dan_chu": "Dân chủ",
        "xu_ly": "Xử lý",
        "dat_ruong": "Đất ruộng",
        "tinh_mat": "Tinh mắt",
        "cung_vay": "Cũng vậy",
        "dung_khong": "Đúng không?",
        "phai_khong": "Phải không?",
        "con_ban": "Còn bạn?",
        "can_khong": "Cần không?",
        "nen_khong": "Nên không?",
        "kia": "Kia",
        "nong_tinh": "Nóng tính",
        "so_khong": "Sợ không?",
        "cam_thu": "Căm thù",
        "dep_khong": "Đẹp không?",
        "khong_dep": "Không đẹp",
        "cac_ban": "Các bạn (2 người)",
        "chung_toi_1": "Chúng tôi",
        "chung_toi_2": "Chúng tôi (2 người)",
        "chung_toi_3": "Chúng tôi (3 người)",
        "chung_toi_4": "Chúng tôi (4 người)",
        "chung_toi_5": "Chúng tôi (5 người)",
        "ho_2": "Họ (2 người)",
        "ho_1": "Họ",
        "sinh_to": "Sinh tố",
        "vat_chanh": "Vắt chanh",
        "mia": "Mía",
        "chanh_da": "Chanh đá",
        "chanh_nong": "Chanh nóng",
        "chanh_muoi": "Chanh muối",
        "tra_da": "Trà đá",
        "tra_nong": "Trà nóng",
        "tra_sua": "Trà sữa",
        "socola": "Socola",
        "cocacola": "CocaCola",
        "7up": "7up",
        "mot_tiet_hoc": "Một tiết học",
        "mot_tieng": "Một tiếng",
        "chung_tay": "Chung tay",
        "rua_chan": "Rửa chân",
        "rua_mat": "Rửa mặt",
        "danh_rang": "Đánh răng",
        "tuan_nay": "Tuần này",
        "tuan_sau": "Tuần sau",
        "tuan_truoc": "Tuần trước",
        "cuoi_tuan": "Cuối tuần",
        "cuoi_thang": "Cuối tháng",
        "cuoi_nam": "Cuối năm",
        "muc_tieu": "Mục tiêu",
        "sinh_doi": "Sinh đôi",
        "doi": "Đôi",
        "dang": "Đảng",
        "mo_ta": "Mô tả",
        "mum_mim": "Mũm mĩm",
        "toc_dai": "Tóc dài",
        "toc_ngan": "Tóc ngắn",
        "tong_ket": "Tổng kết/bế giảng",
        "loc_xoay": "Lốc xoáy",
        "tay_chan_sach_se": "Tay chân sạch sẽ",
        "nham_mat": "Nhắm mắt",
        "so": "Sờ",
        "cay_nen": "Cây nến",
        "diu_dang": "Dịu dàng",
        "dua": "Đùa",
        "lam_duoc": "Làm được",
        "dong_song_chay": "Dòng sông chảy",
        "an_du": "Ăn đủ",
        "an_vua": "Ăn vừa",
        "an_it": "Ăn ít",
        "do_uong": "Đồ uống",
        "do_an": "Đồ ăn",
        "trang_diem": "Trang điểm",
        "dau_mat_do": "Đau mắt đỏ",
        "cai_vot_ca": "Cái vợt cá",
        "vot_cau_long": "Vợt câu lông",
        "con_vuon": "Con vượn",
        "thap_den": "Thắp đèn",
        "gop_tien": "Góp tiền",
        "hop_nhom": "Họp nhóm",
        "nhut_nhat": "Nhút nhát",
        "luoc_rau": "Luộc rau",
        "muoi": "Muối",
        "nuoc_mam": "Nước mắm",
        "thoan_thoat": "Thoăn thoắt",
        "dua_doi": "Đua đòi",
        "binh_sua": "Bình sữa",
        "doi": "Đòi",
        "doi_hoi": "Đòi hỏi",
        "tre_con": "Trẻ con",
        "duy_nhat": "Duy nhất",
        "canh_tranh": "Cạnh tranh",
        "hoa_hau": "Hoa hậu",
        "cai_neo": "Cái neo",
        "phong_vien": "Phóng viên",
        "nha_van_hoa": "Nhà văn hóa",
        "chua_yen_tu": "Chùa Yên Tử",
        "cho_xoi": "Chõ xôi",
        "cay_co": "Cây cọ",
        "khu_vuc_cach_ly": "Khu vực cách ly",
        "ngay_thay_thuoc_VN": "Ngày Thầy thuốc VN",
        "ngay_thanh_lap_QDNDVN": "Ngày thành lập Quân đội Nhân dân Việt Nam",
        "con_ca_sau": "Con cá sấu",
        "nham": "Nhầm",
        "dong_bang_song_CL": "Đồng bằng sông Cửu Long",
        "dong_bang_song_hong": "Đồng bằng sông Hồng",
        "dong_bang_duyen_hai_mien_trung": "Đồng bằng duyên hải miền Trung",
        "buon_tham": "Buồn thảm",
        "mach": "Mách",
        "vo_duyen": "Vô duyên",
        "ti_hi_mat": "Ti hí mắt",
        "kip_thoi": "Kịp thời",
        "boi_roi": "Bối rối",
        "hu_via": "Hú vía",
        "suyts": "Suýt",
        "suytj": "Suỵt",
        "ca_voi": "Cá voi",
        "ca_kiem": "Cá kiếm",
        "duoi_ca": "Đuôi cá",
        "duoi_chuot": "Đuôi chuột",
        "bo_bit_tet": "Bò bít tết",
        "sup": "Súp",
        "sup_lo": "Súp lơ",
        "mi_tom": "Mì tôm",
        "ve_2": "về",
        "ve_3": "về",
        "ve_4": "về",
        "ve_5": "về",
        "hen": "hẹn",
        "quyen_luyen": "quyến luyến",
        "hua": "hứa",
        "cung": "cùng",
        "lau": "lâu",
        "van": "vẫn",
        "moi_ngay": "mỗi ngày",
        "an_bang_thia": "ăn bằng thìa",
        "an_vu_sua": "ăn vú sữa",
        "hoi": "hỏi",
        "trong_nha": "trông nhà",
        "chay": "chạy",
        "xe_container": "xe container",
        "bay_nhanh": "bay nhanh",
        "cham_chap": "chậm chạp",
        "ngung_lai": "ngừng lại",
        "cung_dien": "cung điện",
        "dung_lai": "dừng lại",
        "mot_chut": "một chút",
        "bao_tang": "bảo tàng",
        "bao_thu": "bảo thủ",
        "ton_tai": "tồn tại",
        "bao_ve_moi_truong": "bảo vệ môi trường",
        "bao_conbao": "con báo ",
        "bao_cao": "báo cáo",
        "bao_dong": "báo động",
        "bao_thu": "báo thù",
        "bao": "bát",
        "bat_huong": "bát hương",
        "bat_ngat": "bát ngát",
        "lang_gom_bat_trang": "làng gốm bát tràng",
        "bay": "bay",
        "bay_lieng": "bay liệng(bay lượn)",
        "banh_gai": "bánh gai",
        "banh_giay": "bánh giầy",
        "banh_gio": "bánh giò",
        "banh_goi": "bánh gối",
        "banh_mi": "bánh mì",
        "banh_pizza": "bánh pizza",
        "banh_pia": "bánh pía",
        "hang_tau_thuyen": "hãng tàu thuyền",
        "banh_xe": "bánh xe",
        "bao_gio": "bao giờ",
        "bao_la": "bao la",
        "bao_nhieu": "bao nhiêu",
        "bao_tay": "bao tay  (dùng cho trẻ sơ sinh)",
        "bao_dam": "bao đảm",
        "bao_hiem": "bảo hiểm",
        "luu": "lưu",
        "bang_den": "bảng đen",
        "hang_may_bay": "hãng máy bay",
        "bang_mau": "bảng màu",
        "bang_nhan": "bảng nhân",
        "hang_xe_may": "hãng xe máy",
        "bang_tru": "bảng trừ",
        "bang_bot_loc": "bánh bột lọc",
        "banh_com": "bánh cốm",
        "banh_cuon": "bánh cuốn",
        "banh_trung_thu": "bánh trung thu",
        "banh_da": "bánh đa",
        "banh_duc": "bánh đúc",
        "ban_kinh": "bán kính",
        "ban_gai": "bạn gái",
        "ban_trai": "bạn trai",
        "bang_hoc_sinh": "bảng học sinh",
        "bang_chia": "bảng chia",
        "bang_chi_dan": "bảng chỉ dẫn",
        "bang_chu_cai_ngon_tay": "bảng chữ cái ngón tay",
        "bang_cong": "bảng chữ cái ngón tay",
        "bang_cuu_chuong": "bảng cửu chương",
        "my_van_than": "mỳ vằn thắn",
        "my_y": "mỳ ý",
        "bun_mam": "bún mắm",
        "bun_cha": "bún chả",
        "bun_ngan": "bún ngan",
        "bun_oc": "bún ốc",
        "bun_dau": "bún đậu",
        "xoi_gac": "xôi gấc",
        "xoi_ga": "xôi gà",
        "chao_suon": "cháo sườn",
        "com_rang": "cơm răng",
        "nhan_manh": "nhấn mạnh",
        "dao_dien": "đạo diễn",
        "thi_nghiem": "thí nghiệm",
        "cam_trai": "cắm trại",
        "kha_nang": "khả năng",
        "ky_nang": "kỹ năng",
        "co_khong": "có … không?",
        "cung_cap": "cung cấp",
        "kho_dai": "khờ dại",
        "cuc_kho": "cực khổ",
        "may_man": "may mắn",
        "tu_choi": "từ chối",
        "nau_nuong": "nấu nướng",
        "xoa_dau": "xoa đầu",
        "ruc_ro": "rực rỡ",
        "thiep_sinh_nhat": "thiệp sinh nhật",
        "khong_quen": "không quen",
        "banh_trang": "bánh tráng",
        "tuong_ot": "tương ớt",
        "so_la_ma": "số la mã",
        "long_vuong": "long vương",
        "dang_hoang": "đàng hoàng",
        "phan_van": "phân vân",
        "lau_mieng": "lau miệng",
        "cho_can": "chó cắn",
        "meo_cao": "mèo cào",
        "quan_he_tu": "quan hệ từ",
        "yeu_nuoc_Viet_Nam": "yêu nước Việt Nam",
        "quan": "chức vụ",
        "di_tuan": "đi tuần",
        "vo_ve": "vỗ về",
        "hot_hoang": "hốt hoảng",
        "chuyen_nho": "chuyện nhỏ",
        "cai_gui": "cái gùi",
        "bat_khuat": "bất khuất",
        "nhung": "nhưng",
        "hay_la": "hay là (hoặc là)",
        "thang_long": "thăng long",
        "day_nui_Hoang_Lien_Son": "dãy núi Hoàng Liên Sơn",
        "quanh_nam ": "quanh_năm",
        "gap_doi": "gấp đôi",
        "gap_ba": "gấp ba",
        "chia_doi": "chia đôi",
        "chia_ba": "chia ba",
        "di_lac": "đi lạc",
        "mat": "mất (chết) (chỉ người)",
        "dai_su": "đại sứ",
        "canh_giac": "cảnh giác",
        "giam_sat": "giám sát",
        "quan_sat": "quan sát",
        "an_vung": "ăn vụng",
        "xay_ra": "xảy ra",
        "du_an": "dự án",
        "dau_tu": "đầu tư",
        "nan_ni": "năn nỉ",
        "hao_huc": "háo hức",
        "rac_roi": "rắc rối",
        "tai_ve": "tải về",
        "nhong_nheo": "nhỏng nhẽo",
        "hen": "hên",
        "den_dui": "đen đủi",
        "long_lanh": "long lanh",
        "lanh_lung": "lạnh lùng",
        "doi": "dỗi",
        "liec_nhin": "liếc nhìn",
        "nho_toc": "nhổ tóc",
        "nho_rau": "nhổ râu",
        "nho_long_may": "nhổ lông mày",
        "cat_long_mui": "cắt lông mũi",
        "nho_rang": "nhổ răng",
        "rang_ho": "rang hô",
        "rang_khenh": "rang khểnh",
        "khau_khinh": "kháu khỉnh",
        "moc_toc": "mọc tóc",
        "moc_rau": "mọc râu",
        "moc_ria_mep": "mọc ria mép",
        "covid": "covid",
        "co_do_hue": "Cố đô Huế",
        "cach_ly": "cách ly",
        "gian_cach_xa_hoi": "giản cách xã hội",
        "tuong_lai": "tương lai",
        "trong_khoang": "trong khoảng",
        "tron_tim": "trốn tìm",
        "nhay_bao_bo": "nhảy bao bố",
        "nhay_lo_co": "nhảy lò cò",
        "keo_co": "kéo co",
        "hoi_thoai": "hội thoại",
        "ly_do": "lý do",
        "lon_hon_mot_toan_hoc": "lớn hơn 1 (Toán học)",
        "lon_hon_hai_toan_hoc": "lớn hơn 2 (Toán học)",
        "hai_nho_hon_nam_toan_hoc": "2 < 5 (Toán học)",
        "tinh_tao": "tỉnh táo",
        "nhon_nhip_dong_nguoi": "nhộn nhịp (đông người)",
        "ao_ke_soc": "áo kẻ sọc",
        "dat_nuoc_bi_chia_cat_viet_nam": "đất nước bị chia cắt (Việt Nam)",
        "thong_nhat_dat_nuoc": "thống nhất đất nước",
        "khoang_san": "khoáng sản",
        "thuong_mai": "thương mại",
        "cong_nghiep": "công nghiệp",
        "hap_dan": "hấp dẫn",
        "100": "100.npy",
        "1000": "1000.npy",
        "5000": "5000.npy",
        "10000": "10000.npy",
        "ac_cam": "ac_cam.npy",
        "ac_mong": "ac_mong.npy",
        "ac": "ac.npy",
        "mot_trieu": "mot_trieu.npy",
        "mot_ty": "mot_ty.npy",
        "ai": "ai",
        "am_ap": "ẩm ấp",
        "am_moc": "ẩm mốc",
        "am_no": "ấm no",
        "am_thanh": "âm thanh",
        "am_uot": "ẩm ướt",
        "an_dien": "ăn diện",
        "an_giang": "An Giang",
        "an_hoi_lo": "ăn hối lộ",
        "an_tuong": "ấn tượng",
        "an_uong": "ăn uống",
        "an_xin": "ăn xin",
        "an": "ăn",
        "anh_chi_em": "anh chị em",
        "anh_chi": "anh chị",
        "anh_dung": "anh dũng",
        "anh_em": "anh em",
        "anh_ho": "anh họ",
        "anh_re": "anh rể",
        "anh_ruot": "anh ruột",
        "anh_vo": "anh vợ",
        "ao_am": "áo ấm",
        "ao_canh": "áo cánh",
        "ao_dong_phuc": "áo đồng phục",
        "ao_len": "áo len",
        "ao_phao": "áo phao",
        "ao_phong": "áo phông",
        "ao_thuat": "ảo thuật",
        "ao": "áo",
        "ap_phich": "áp phích",
        "bai_bao": "bài báo",
        "bai_cat": "bãi cát",
        "bai_co": "bãi cỏ",
        "bai_do_xe": "bãi đỗ xe",
        "bai_tam": "bãi tắm",
        "bai_tho": "bài thơ",
        "ban_dem": "ban đêm",
        "ban_giam_hieu": "ban giám hiệu",
        "ban_ngay": "ban ngày",
        "he_bai_tiet": "hệ bài tiết",
        "nuoc_anh": "nước Anh",
        "sang": "sáng",
        "buoi_toi": "Buổi tối",
        "buoi_trua": "Buổi trưa",
        "buon_lang": "Buôn làng",
        "buon_non": "Buồn nôn",
        "buong_man": "Buông màn",
        "buong_trung": "Buồng trứng",
        "bup_be": "Búp bê",
        "but": "Bút",
        "but_bi": "Bút bi",
        "but_da": "Bút dạ",
        "buc_tranh": "Bức tranh",
        "buc_tuong": "Bức tường",
        "buoc": "Bước",
        "buoc_chan": "Bước chân",
        "buong_binh": "Bướng bỉnh",
        "buu_ta": "Bưu tá",
        "ca": "Ca",
        "ca_mau": "Cà Mau",
        "cai_nhau": "Cãi nhau",
        "cai_be": "Cái bè",
        "cam_pu_chia": "Cam-pu-chia",
        "cai_tui": "Cái túi",
        "canh_tay": "Cánh tay",
        "canh": "Cạnh",
        "canh_day": "Cạnh đáy",
        "canh_ben": "Cạnh bên",
        "canh_doi_dien": "Cạnh đối diện",
        "cao_nguoi": "Cao (người)",
        "cao_vat": "Cao (vật)",
        "cao_do": "Cao độ",
        "cao_nha": "Cao (nhà)",
        "cao_quy": "Cao quý",
        "cat": "Cát",
        "cau_co": "Cau có",
        "cay": "Cày",
        "cay_ruong": "Cày ruộng",
        "cap_sach": "Cặp sách",
        "cap_toc": "Cặp tóc",
        "cat_nhau": "Cắt nhau",
        "can_khoi_dong": "Cần khởi động",
        "cap_cuu": "Cấp cứu",
        "cap_duong": "Cấp dưỡng",
        "cat_giau": "Cất giấu",
        "cat_tieng_khoc": "Cất tiếng khóc",
        "cau_ca": "Câu cá",
        "cau_chuyen": "Câu chuyện",
        "cau_doi": "Câu đối",
        "cau_do": "Câu đố",
        "cau_ghep": "Câu ghép",
        "cau_tho": "Câu thơ",
        "cau_van": "Câu văn",
        "cay_cau": "Cầu (cây cầu)",
        "cau_cuu": "Cầu cứu",
        "cau_giao": "Cầu giao",
        "cau_nguyen": "Cầu nguyện",
        "cau_thu": "Cầu thủ",
        "cap_treo": "Cáp treo",
        "cau_truot": "Cầu trượt",
        "cau_vuot": "Cầu vượt",
        "cay_an_qua": "Cây ăn quả",
        "bit_tat": "Bít tất",
        "bof": "Bò",
        "bo_sat": "Bò sát",
        "bo_tot": "Bò tót",
        "bo_hoang": "Bỏ hoang",
        "bo_phieu": "Bỏ phiếu",
        "bo_qua": "Bỏ qua",
        "bo_roi": "Bỏ rơi",
        "bo_dua": "Bó đũa",
        "bo_hoa": "Bó hoa",
        "boc_lot": "Bóc lột",
        "boc_vo": "Bóc vỏ",
        "boc_sach": "Bọc sách",
        "bom_dan": "Bom đạn",
        "bom_nguyen_tu": "Bom nguyên tử",
        "bon_phan": "Bón phân",
        "bong": "Bỏng",
        "bong_ngo": "Bỏng ngô",
        "bong_bay": "Bóng bay",
        "boong_tau": "Boong tàu",
        "bot_bien": "Bọt biển",
        "bot_xa_phong": "Bọt xà phòng",
        "bo_ket": "Bồ kết",
        "bo_ich": "Bổ ích",
        "bo_ngu": "Bổ ngữ",
        "bo_tro": "Bổ trợ",
        "bo_tri": "Bố trí",
        "bo_truyen": "Bộ truyện",
        "boc_vac": "Bốc vác",
        "boos": "Bố",
        "bo_duong": "Bố dượng",
        "bo_me": "Bố mẹ",
        "bo_doi": "Bộ đội",
        "bo_sach": "Bộ sách",
        "boc_hoi": "Bốc hơi",
        "boc_tham": "Bốc thăm",
        "boi_ban": "Bồi bàn",
        "boi_thuong": "Bồi thường",
        "bon_hoa": "Bồn hoa",
        "bon_rua_bat": "Bồn rửa bát",
        "bong_hoa": "Bông hoa",
        "bot_canh_sat": "Bốt cảnh sát",
        "bot_dien": "Bốt điện",
        "bot_giat": "Bột giặt",
        "bot_mau": "Bột màu",
        "bot_ngot": "Bột ngọt",
        "bo_bien": "Bờ biển",
        "bo_rao": "Bờ rào",
        "bo_ruong": "Bờ ruộng",
        "boi": "Bơi",
        "boi_loi": "Bơi lội",
        "bom": "Bơm (cái bơm)",
        "bom_nuoc": "Bơm nước",
        "bom_xe": "Bơm xe",
        "bom_toc": "Bờm tóc",
        "bot": "Bớt",
        "bot_di": "Bớt đi",
        "bra_xin": "Nước Bra-xin",
        "bru_nay": "Nước Bru-nây",
        "co": "Cỏ",
        "bui_doi": "Bụi đời",
        "bui_phan": "Bụi phấn",
        "bun_ga_ri": "Nước Bun-ga-ri",
        "bun": "Bùn",
        "bung": "Bụng",
        "buoc_day": "Buộc dây",
        "buoc_toc": "Buộc tóc",
        "buoi_chieu": "Buổi chiều",
        "buoi_dem": "Buổi đêm",
        "buoi_sang": "Buổi sáng",
        "ban_bac": "bàn bạc",
        "ban_chai_danh_rang": "bàn chải dánh răng",
        "ban_chan": "bàn chân",
        "ban_ghe": "bàn ghế",
        "ban_la": "bàn là",
        "ban_phim_may_vi_tinh": "bàn phím máy vi tính",
        "ban_tay": "bàn tay",
        "ban_tan": "bàn tán",
        "ban_do_viet_nam": "bản đồ việt nam",
        "ban_lang": "bản làng",
        "ban_le": "bản lề",
        "ban_nhac": "bản nhạc",
        "ban_sao_chi_nguoi": "bản sao (chỉ người)",
        "ban_than": "bản thân",
        "ban_buon": "bản buôn",
        "ban_dao": "bản đảo",
        "ban_hang": "bán hàng",
    }

    def __init__(self, min_frames_per_gesture=5, similarity_threshold=0.7):
        self.predictions = []  # Lưu tất cả predictions theo thời gian
        self.current_gesture = None
        self.gesture_start_frame = 0
        self.min_frames_per_gesture = min_frames_per_gesture
        self.similarity_threshold = similarity_threshold
        self.sequence = []  # Chuỗi cử chỉ đã nhận diện

    def receive(self, prediction):
        # Chuyển đổi prediction thành dạng chuẩn (lowercase) để so sánh
        normalized_prediction = (
            prediction.strip().lower()
            if isinstance(prediction, str)
            else str(prediction)
        )
        self.predictions.append(normalized_prediction)

        # Nếu cử chỉ thay đổi
        if self.current_gesture != normalized_prediction:
            # Nếu cử chỉ cũ tồn tại đủ lâu, thêm vào sequence (đã mapped)
            if (
                self.current_gesture
                and len(self.predictions) - self.gesture_start_frame
                >= self.min_frames_per_gesture
            ):
                mapped_gesture = self.MAPPING.get(
                    self.current_gesture, self.current_gesture
                )
                self.sequence.append(mapped_gesture)

            self.current_gesture = normalized_prediction
            self.gesture_start_frame = len(self.predictions)

    def get_sequence(self):
        if (
            self.current_gesture
            and len(self.predictions) - self.gesture_start_frame >= self.min_frames_per_gesture
        ):
            mapped_gesture = self.MAPPING.get(
                self.current_gesture, self.current_gesture)
            self.sequence.append(mapped_gesture)

        # Chỉ join bằng dấu phẩy, không ghép ký tự đơn
        return ", ".join([g.strip() for g in self.sequence])

    def get_message(self):
        sequence = self.get_sequence()
        # Đảm bảo chuỗi kết quả được format đẹp
        return sequence.strip()

    def get_raw_predictions(self):
        """Trả về chuỗi predictions gốc (cho debug)"""
        return "".join(self.predictions)

    def receive_old(self, message):
        self.current_message = message

    def get_message_old(self):
        return ExpressionHandler.MAPPING.get(self.current_message, self.current_message)

    @classmethod
    def get_display_text(cls, key: str) -> str:
        """Lấy value từ key, nếu không có thì trả về key gốc"""
        return cls.MAPPING.get(key, key)
